# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenecQR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 294)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_View = QtWidgets.QGraphicsView(self.centralwidget)
        self.img_View.setGeometry(QtCore.QRect(10, 20, 281, 211))
        self.img_View.setObjectName("img_View")
        self.btn_Gen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Gen.setGeometry(QtCore.QRect(330, 190, 141, 41))
        self.btn_Gen.setObjectName("btn_Gen")
        self.lEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lEdit.setGeometry(QtCore.QRect(310, 60, 191, 31))
        self.lEdit.setText("")
        self.lEdit.setObjectName("lEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.l_Png = QtWidgets.QLineEdit(self.centralwidget)
        self.l_Png.setGeometry(QtCore.QRect(310, 140, 191, 31))
        self.l_Png.setText("")
        self.l_Png.setObjectName("l_Png")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Gen.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Enter Text :"))
        self.label_2.setText(_translate("MainWindow", "Image Format :"))
